### ISSUE TITLE
Plugin crashes Spyder v6

### ISSUE THREAD

**Issue by schmoelder** [ok97465/spyder_okvim#52]
When starting spyder v6, I get the following error message:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QWidget::setLayout: Attempting to set QLayout "" on StatusBarVimWidget "", which already has a layout
<class 'spyder_okvim.spyder.plugin.OkVim'>: 'Editor' object has no attribute 'editorsplitter'
Traceback (most recent call last):
  File "/home/jo/software/miniforge3/envs/dev/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 761, in setup
    plugin_instance = PLUGIN_REGISTRY.register_plugin(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jo/software/miniforge3/envs/dev/lib/python3.11/site-packages/spyder/api/plugin_registration/registry.py", line 344, in register_plugin
    instance = self._instantiate_spyder5_plugin(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jo/software/miniforge3/envs/dev/lib/python3.11/site-packages/spyder/api/plugin_registration/registry.py", line 195, in _instantiate_spyder5_plugin
    plugin_instance.initialize()
  File "/home/jo/software/miniforge3/envs/dev/lib/python3.11/site-packages/spyder/api/plugins/new_api.py", line 708, in initialize
    self.on_initialize()
  File "/home/jo/software/miniforge3/envs/dev/lib/python3.11/site-packages/spyder_okvim/spyder/plugin.py", line 140, in on_initialize
    vim_cmd.editor_widget.editorsplitter,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Editor' object has no attribute 'editorsplitter'
[1]    222767 segmentation fault (core dumped)  spyder
```

**Comment by schmoelder** [comment]
It appears the crash comes from these lines

https://github.com/ok97465/spyder_okvim/blob/af9467a4393d2b696fda95b6c6845ecdc8c104a7/spyder_okvim/spyder/plugin.py#L138C1-L143C53

If I change them to the following:
```
        sc = QShortcut(
            QKeySequence("Esc"),
            vim_cmd.editor_widget.get_widget().editorsplitter,
            vim_cmd.commandline.setFocus,
        )
        sc.setContext(Qt.WidgetWithChildrenShortcut)
```

Spyder does not crash anymore, the (empty) pane shows but the plugin does not work yet.

**Comment by ok97465** [comment]
Sorry for the late response.
My plugin doesn't seem to work with Spyder6 yet.
I'll take my time looking into it this weekend.

**Comment by schmoelder** [comment]
Thanks mate, I would really appreciate it! Let me know if I can be of help! :nerd_face:

**Comment by schmoelder** [comment]
Anything I can do to help? I'd also be willing to sponsor this plugin with 25 €.

**Comment by ok97465** [comment]
> Anything I can do to help? I'd also be willing to sponsor this plugin with 25 €.

Thank you so much for your interest in my plugin.
I want to solve the problem quickly, but things aren't going well at work, so it's difficult to find personal time. I'm sorry.

**Comment by ok97465** [comment]
@schmoelder 

I’m sorry for closing this issue so late, even though it was opened back in September 2024.
If you’re still using Spyder, I hope my plugin continues to be helpful to you.
Thank you!

**Comment by schmoelder** [comment]
Hi, thank you so much. I really appreciate it! 🥳 

I did have an issue on installation, though:

```
❯ pip install --upgrade .
Processing ~/software/spyder_okvim
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of spyder-okvim to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement python>=3.9 (from spyder-okvim) (from versions: none)
ERROR: No matching distribution found for python>=3.9
```

I presume, the issue is with the `setup.py`. Modifying it to
```
  23   │   python_requires='>=3.9',
  24   │   install_requires=[
  25   │   │   "spyder>6"
   26   │   ],
```
fixes the issue and it works like a charm! :)
